name: chatgpt_playlist_download
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.31
  mockito: ^5.3.2
  path_provider: ^2.0.13
  provider: ^6.0.5
  youtube_explode_dart: ^1.12.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
